### ISSUE TITLE
Monitor event condition is deleted when issuing `serverless deploy`

### ISSUE THREAD

**Issue by mhpaler** [OpenZeppelin/defender-as-code#52]
Whenever I deploy my config (via `serverless deploy`), the Event Condition is removed from the monitor and I need to manually set it in the admin ui. Any suggestions greatly appreciated.

    "@openzeppelin/defender-as-code": "^2.6.0",
    "serverless": "^3.38.0",

```yaml
service: defender-ets
configValidationMode: error
frameworkVersion: "3"
useDotenv: true
provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: "mystack"
  ssot: false
#custom:
#  config: ${file(secrets.${self:provider.stage}.yml)}
defender:
  key: "${env:TEAM_API_KEY}"
  secret: "${env:TEAM_API_SECRET}"
resources:
  actions:
    release-next-auction:
      name: ReleaseNextAuction
      relayer: ${self:resources.relayers.ets-auction-oracle}
      trigger:
        type: sentinel
      paused: false
      path: "./dist/defender/actions/release-next-auction"
      environment-variables:
        NETWORK: "mumbai_stage"
        NEXT_PUBLIC_ETS_ENVIRONMENT: "stage"
  policies:
    policy-zz:
      eip1559-pricing: true
      private-transactions: false
  contracts:
    ets-auction-house:
      name: ETSAuctionHouse
      address: "0xf5d631DC08211e649FA7B025179De146AfFAEe41"
      network: mumbai
      abi: ${file(./abi/ETSAuctionHouse.json.abi)}
  relayers:
    ets-auction-oracle:
      name: "ETSAuctionOracle"
      network: "mumbai"
      min-balance: "100000000000000000"
      policy: ${self:resources.policies.policy-zz}
      api-keys:
        - key-1
  categories:
    low-severity:
      name: Low Severity
      description: A default category to be assigned for low risk monitors.
      notification-ids:
        - ${self:resources.notifications.discord-actitity-internal}
    medium-severity:
      name: Medium Severity
      description: A default category to be assigned for medium risk monitors.
    high-severity:
      name: High Severity
      description: A default category to be assigned for high risk monitors.
  monitors:
    request-create-auction:
      name: RequestCreateAuction
      type: BLOCK
      network: mumbai
      addresses:
        - "0xf5d631DC08211e649FA7B025179De146AfFAEe41"
      skip-abi-validation: false
      paused: false
      action-trigger: ${self:resources.actions.release-next-auction}
      confirm-level: 1
      conditions:
        event:
          - signature: RequestCreateAuction()
  forked-networks: {}
  private-networks: {}
  block-explorer-api-keys: {}
plugins:
  - "@openzeppelin/defender-as-code"
```
